base_config: src/heatmap/config_overhead_default.yaml

match:
  id: f_match_1
  input_video: footages/f_match_1.mp4

video:
  duration_seconds: 368.567

sampling:
  stop_seconds: 330.0

frame_quality:
  invalid_ranges_seconds:
    - [0.0, 19.9]
    - [340.0, 368.6]
