from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Sequence


@dataclass(frozen=True)
class CheckStep:
    name: str
    command: Sequence[object]


def tooling_smoke_steps(python: Path, work_dir: Path, match_video: str, device: str) -> list[CheckStep]:
    annotation_dir = work_dir / "annotation_samples"
    return [
        CheckStep("inventory helper", [python, "scripts/inventory_project.py", "--output", work_dir / "project_inventory.json"]),
        CheckStep("csv report helper", [python, "scripts/report_csv.py", work_dir / "sample.csv", "--output", work_dir / "sample.report.md"]),
        CheckStep(
            "heatmap annotation package helper",
            [
                python,
                "scripts/export_heatmap_annotation_package.py",
                "--output-dir",
                annotation_dir,
                "--match-id",
                "match_9",
                "--frames-per-match",
                "1",
            ],
        ),
        CheckStep(
            "heatmap annotation evaluation helper",
            [
                python,
                "scripts/evaluate_heatmap_annotations.py",
                annotation_dir / "annotation_template.csv",
                "--output",
                annotation_dir / "evaluation.json",
                "--report",
                annotation_dir / "evaluation.md",
            ],
        ),
        CheckStep("heatmap config validation helper", [python, "scripts/validate_heatmap_configs.py", "--strict"]),
        CheckStep(
            "heatmap anomaly export helper",
            [
                python,
                "scripts/export_heatmap_anomalies.py",
                "--output-dir",
                work_dir / "heatmap_anomalies",
                "--match-id",
                "match_9",
                "--max-items-per-match",
                "4",
            ],
        ),
        CheckStep(
            "heatmap comparison helper",
            [
                python,
                "scripts/report_heatmap_comparison.py",
                "--output",
                work_dir / "heatmap_comparison.md",
                "--json-output",
                work_dir / "heatmap_comparison.json",
                "--strict",
            ],
        ),
        CheckStep("weapon training plan helper", [python, "scripts/plan_weapon_training.py"]),
        CheckStep("weapon training strict plan helper", [python, "scripts/plan_weapon_training.py", "--strict"]),
        CheckStep(
            "weapon classifier training dry run",
            [
                python,
                "scripts/train_weapon_classifier.py",
                "--dry-run",
                "--max-samples-per-class",
                "1",
                "--epochs",
                "1",
                "--batch-size",
                "8",
                "--output",
                work_dir / "weapon_model.pth",
                "--metrics",
                work_dir / "weapon_training_metrics.json",
            ],
        ),
        CheckStep(
            "weapon synthetic dataset dry run",
            [
                python,
                "scripts/generate_weapon_dataset.py",
                "--dry-run",
                "--images-per-class",
                "1",
                "--output-dir",
                work_dir / "generated_weapon_dataset",
            ],
        ),
        CheckStep(
            "match intake dry run",
            [
                python,
                "scripts/intake_match.py",
                "--match-id",
                "match_intake_smoke",
                "--video",
                match_video,
                "--analysis-id",
                "match_intake_smoke_10_20",
                "--start-seconds",
                "10",
                "--stop-seconds",
                "20",
                "--sample-fps",
                "5",
                "--device",
                device,
                "--dry-run",
                "--report",
                work_dir / "match_intake.md",
            ],
        ),
        CheckStep(
            "sample intake dry run",
            [
                python,
                "scripts/intake_samples.py",
                "--video",
                match_video,
                "--match-id",
                "sample_intake_smoke",
                "--report",
                work_dir / "sample_intake.md",
                "--json-output",
                work_dir / "sample_intake.json",
                "--strict",
            ],
        ),
        CheckStep(
            "model quality overview helper",
            [
                python,
                "scripts/report_model_quality.py",
                "--output",
                work_dir / "model_quality.md",
                "--json-output",
                work_dir / "model_quality.json",
            ],
        ),
        CheckStep(
            "project hygiene report helper",
            [
                python,
                "scripts/report_project_hygiene.py",
                "--output",
                work_dir / "project_hygiene.md",
                "--json-output",
                work_dir / "project_hygiene.json",
            ],
        ),
        CheckStep(
            "yolov5 vendor boundary helper",
            [
                python,
                "scripts/report_yolov5_vendor.py",
                "--output",
                work_dir / "yolov5_vendor.md",
                "--json-output",
                work_dir / "yolov5_vendor.json",
                "--strict",
            ],
        ),
        CheckStep(
            "dataset governance report helper",
            [
                python,
                "scripts/report_dataset_governance.py",
                "--output",
                work_dir / "dataset_governance.md",
                "--json-output",
                work_dir / "dataset_governance.json",
            ],
        ),
        CheckStep(
            "model registry report helper",
            [
                python,
                "scripts/report_model_registry.py",
                "--output",
                work_dir / "model_registry.md",
                "--json-output",
                work_dir / "model_registry.json",
                "--strict",
            ],
        ),
        CheckStep(
            "model training plan helper",
            [
                python,
                "scripts/plan_model_training.py",
                "--output",
                work_dir / "model_training_plan.md",
                "--json-output",
                work_dir / "model_training_plan.json",
            ],
        ),
        CheckStep(
            "model training dataset dry run helper",
            [
                python,
                "scripts/validate_model_training_datasets.py",
                "--output",
                work_dir / "model_training_datasets.md",
                "--json-output",
                work_dir / "model_training_datasets.json",
            ],
        ),
        CheckStep(
            "heatmap quality loop helper",
            [
                python,
                "scripts/report_heatmap_quality_loop.py",
                "--output",
                work_dir / "heatmap_quality_loop.md",
                "--json-output",
                work_dir / "heatmap_quality_loop.json",
            ],
        ),
    ]


def model_error_steps(python: Path, work_dir: Path) -> list[CheckStep]:
    return [
        CheckStep(
            "model error report helper",
            [
                python,
                "scripts/report_model_errors.py",
                "--csv",
                work_dir / "sample.csv",
                "--output",
                work_dir / "model_errors.md",
                "--json-output",
                work_dir / "model_errors.json",
            ],
        )
    ]


def heatmap_annotation_steps(python: Path, work_dir: Path) -> list[CheckStep]:
    annotation_csv = work_dir / "heatmap_annotation_round1" / "annotation_template.csv"
    return [
        CheckStep(
            "heatmap annotation round helper",
            [
                python,
                "scripts/prepare_heatmap_annotation_round.py",
                "--package-dir",
                work_dir / "heatmap_annotation_round1",
                "--output",
                work_dir / "heatmap_annotation_round1.md",
                "--json-output",
                work_dir / "heatmap_annotation_round1.json",
            ],
        ),
        CheckStep(
            "heatmap annotation UI helper",
            [
                python,
                "scripts/build_heatmap_annotation_ui.py",
                "--annotation-csv",
                annotation_csv,
                "--output",
                work_dir / "heatmap_annotation_round1" / "annotation_ui.html",
                "--json-output",
                work_dir / "heatmap_annotation_ui.json",
            ],
        ),
        CheckStep(
            "heatmap tuning suggestion helper",
            [
                python,
                "scripts/suggest_heatmap_tuning.py",
                "--annotation-csv",
                annotation_csv,
                "--heatmap-comparison",
                work_dir / "heatmap_comparison.json",
                "--output",
                work_dir / "heatmap_tuning_suggestions.md",
                "--json-output",
                work_dir / "heatmap_tuning_suggestions.json",
            ],
        ),
        CheckStep(
            "heatmap parameter experiment helper",
            [
                python,
                "scripts/run_heatmap_parameter_experiments.py",
                "--annotation-csv",
                annotation_csv,
                "--output-root",
                work_dir / "heatmap_parameter_experiments",
                "--write-configs",
                "--output",
                work_dir / "heatmap_parameter_experiments.md",
                "--json-output",
                work_dir / "heatmap_parameter_experiments.json",
            ],
        ),
    ]


def experiment_delivery_steps(python: Path, root: Path, work_dir: Path) -> list[CheckStep]:
    return [
        CheckStep(
            "runtime wrapper helper",
            [
                python,
                "scripts/run_with_runtime_report.py",
                "--name",
                "summarize_sample_csv",
                "--output",
                work_dir / "runtime_summary.json",
                "--markdown-output",
                work_dir / "runtime_summary.md",
                "--",
                str(python),
                "scripts/summarize_csv.py",
                str(work_dir / "sample.csv"),
            ],
        ),
        CheckStep(
            "runtime benchmark report helper",
            [
                python,
                "scripts/report_runtime_benchmarks.py",
                "--runtime-report",
                f"summarize_sample_csv={work_dir / 'runtime_summary.json'}",
                "--output",
                work_dir / "runtime_benchmarks.md",
                "--json-output",
                work_dir / "runtime_benchmarks.json",
            ],
        ),
        CheckStep(
            "model experiment plan helper",
            [
                python,
                "scripts/plan_model_experiments.py",
                "--model-errors",
                work_dir / "model_errors.json",
                "--heatmap-comparison",
                work_dir / "heatmap_comparison.json",
                "--output",
                work_dir / "model_experiment_plan.md",
                "--json-output",
                work_dir / "model_experiment_plan.json",
            ],
        ),
        CheckStep(
            "model benchmark plan helper",
            [
                python,
                "scripts/benchmark_model_experiments.py",
                "--experiment-plan",
                work_dir / "model_experiment_plan.json",
                "--heatmap-comparison",
                work_dir / "heatmap_comparison.json",
                "--output",
                work_dir / "model_benchmark_plan.md",
                "--json-output",
                work_dir / "model_benchmark_plan.json",
            ],
        ),
        CheckStep(
            "model benchmark baseline helper",
            [
                python,
                "scripts/report_model_benchmark_baseline.py",
                "--evaluation-results",
                root / "outputs" / "evaluation" / "evaluation_results.json",
                "--model-errors",
                work_dir / "model_errors.json",
                "--heatmap-comparison",
                work_dir / "heatmap_comparison.json",
                "--heatmap-quality-loop",
                work_dir / "heatmap_quality_loop.json",
                "--benchmark-plan",
                work_dir / "model_benchmark_plan.json",
                "--output",
                work_dir / "model_benchmark_baseline.md",
                "--json-output",
                work_dir / "model_benchmark_baseline.json",
            ],
        ),
        CheckStep(
            "experiment manifest helper",
            [
                python,
                "scripts/write_experiment_manifest.py",
                "--experiment-id",
                "check_project_tooling",
                "--artifact",
                f"model_benchmark_baseline={work_dir / 'model_benchmark_baseline.json'}",
                "--artifact",
                f"heatmap_parameter_experiments={work_dir / 'heatmap_parameter_experiments.json'}",
                "--verification",
                "check_project --tooling helper smoke",
                "--output",
                work_dir / "experiment_manifest.md",
                "--json-output",
                work_dir / "experiment_manifest.json",
            ],
        ),
        CheckStep(
            "heatmap productization helper",
            [
                python,
                "scripts/report_heatmap_productization.py",
                "--annotation-round",
                work_dir / "heatmap_annotation_round1.json",
                "--tuning-report",
                work_dir / "heatmap_tuning_suggestions.json",
                "--heatmap-comparison",
                work_dir / "heatmap_comparison.json",
                "--runtime-benchmarks",
                work_dir / "runtime_benchmarks.json",
                "--output",
                work_dir / "heatmap_productization.md",
                "--json-output",
                work_dir / "heatmap_productization.json",
            ],
        ),
        CheckStep(
            "training sample candidate export helper",
            [
                python,
                "scripts/export_training_sample_candidates.py",
                "--evaluation-results",
                root / "outputs" / "validation_suite" / "evaluation" / "evaluation_results.json",
                "--model-training-plan",
                work_dir / "model_training_plan.json",
                "--output-dir",
                work_dir / "training_sample_candidates",
                "--no-frame-export",
                "--no-heatmap",
                "--output",
                work_dir / "training_sample_candidates.md",
                "--json-output",
                work_dir / "training_sample_candidates.json",
            ],
        ),
        CheckStep(
            "model data readiness helper",
            [
                python,
                "scripts/report_model_data_readiness.py",
                "--annotation-round",
                work_dir / "heatmap_annotation_round1.json",
                "--parameter-experiments",
                work_dir / "heatmap_parameter_experiments.json",
                "--runtime-benchmarks",
                work_dir / "runtime_benchmarks.json",
                "--dataset-governance",
                work_dir / "dataset_governance.json",
                "--model-registry",
                work_dir / "model_registry.json",
                "--model-training-plan",
                work_dir / "model_training_plan.json",
                "--model-training-datasets",
                work_dir / "model_training_datasets.json",
                "--model-experiment-plan",
                work_dir / "model_experiment_plan.json",
                "--output",
                work_dir / "model_data_readiness.md",
                "--json-output",
                work_dir / "model_data_readiness.json",
            ],
        ),
        CheckStep(
            "stage coordinate normalization helper",
            [
                python,
                "scripts/report_stage_coordinates.py",
                "--config",
                "src/heatmap/config_match9.yaml",
                "--output",
                work_dir / "stage_coordinates.md",
                "--json-output",
                work_dir / "stage_coordinates.json",
            ],
        ),
        CheckStep(
            "change package helper",
            [
                python,
                "scripts/report_change_package.py",
                "--verification",
                "check_project --tooling helper smoke",
                "--output",
                work_dir / "change_package.md",
                "--json-output",
                work_dir / "change_package.json",
            ],
        ),
    ]
